services:
  api_gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: always
    ports:
      - "3000:3000"
    environment:
      GATEWAY_PORT: 3000
      BOOKING_SERVICE_URL: http://booking_service:5000
      CORS_ORIGIN: "*"
    depends_on:
      - booking_service
    networks:
      - evcs_network

  booking_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: booking_service
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: evcs_mysql         
      MYSQL_USER: root
      MYSQL_PASSWORD: 292902
      MYSQL_DB: evcsms_db
      PORT: 5000
    depends_on:
      - evcs_mysql
    networks:
      - evcs_network

  evcs_mysql:
    image: mysql:8.0
    container_name: evcs_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 292902
      MYSQL_DATABASE: evcsms_db
    ports:
      - "3307:3306"               
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - evcs_network

volumes:
  mysql_data:

networks:
  evcs_network:
    driver: bridge
